config/routes.rb
Rails.application.routes.draw do
  get 'schedules/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :schedules
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/schedule.rb
class Schedule < ApplicationRecord
 validates :title, presence: true
 validates :startDate, presence: true
 validates :endDate, presence: true

 validate :date_before_start
 validate :date_before_finish

 def date_before_start
  return if startDate.blank?
  errors.add(:startDate, "は今日以降の日付を選択してください") if startDate < Date.today
 end

 def date_before_finish
  return if endDate.blank? || startDate.blank?
  errors.add(:endDate, "は開始日以降の日付を選択してください") if endDate < startDate
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def index
    @schedules = Schedule.all
  end
  
  def new
    @schedule = Schedule.new
  end
  
  def create
    @schedule = Schedule.new(params.require(:schedule).permit(:title, :startDate, :endDate, :allDay, :memo))
    if @schedule.save
      flash[:notice] = "スケジュールを登録しました"
      redirect_to :schedules
    else
      flash[:alert] = "スケジュールを登録できませんでした"
      render "new", status: :unprocessable_entity
    end
  end
  
  def show
    @schedule = Schedule.find(params[:id])
  end
  
  def edit
    @schedule = Schedule.find(params[:id])
  end
  
  def update
    @schedule = Schedule.find(params[:id])
    if @schedule.update(params.require(:schedule).permit(:title, :startDate, :endDate, :allDay, :memo))
      flash[:notice] = "ID「#{@schedule.id}」のスケジュールを更新しました"
      redirect_to :schedules
    else
      render "edit"
    end
  end
  
  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy
    flash[:warning] = "ID「#{@schedule.id}」のスケジュールを削除しました"
    redirect_to @schedule, status: :see_other
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <h1>Ruby on Rails スケジュール管理アプリ</h1>
    </header>
    <%= yield %>
    <footer>
      <h1>現在の日付：<%= Date.current.strftime('%Y年 %m月 %d日')%>　スケジュール合計：<%= Schedule.count %></h1>
    </footer>
  </body>
</html>

app/views/schedules/edit.html.erb
<h3 class="title">スケジュール編集</h3>

<%= form_with model: @schedule do |f| %>

 <table>
  <tr>
   <th><%= f.label :title ,"タイトル" %></th>
   <td><%= f.text_field :title, style: "width:100%" %></td>
  </tr>
 
  <tr>
   <th><%= f.label :startDate ,"開始日" %></th>
   <td><%= f.date_field :startDate, style: "width:100%" %></td>
  </tr>
 
  <tr>
   <th><%= f.label :endDate ,"終了日" %></th>
   <td><%= f.date_field :endDate, style: "width:100%" %></td>
  </tr>
 
  <tr>
   <th><%= f.label :allDay ,"終日" %></th>
   <td align="center"><%= f.check_box :allDay %><br>
   終日の場合はチェックを入れます</td>
  </tr>
 
  <tr>
   <th class="memo"><%= f.label :memo ,"スケジュールメモ" %></th>
   <td><%= f.text_area :memo, style: "height: 200px; width:100%" %></td>
  </tr>
 </table>

 <div>
  <ul style="list-style: none;" >
   <li><%= f.submit "スケジュールの編集を完了する", style: "font-size: 15px" %></li>
   <li><%= link_to "スケジュール一覧に戻る", :schedules %></li>
  </ul>
 </div>
<% end %>

app/views/schedules/index.html.erb
<h3 class="title">スケジュール一覧</h3>

<% if flash[:notice] %>
 <p class = "notice"><%= flash[:notice] %></p>
<% end %>

<% if flash[:warning] %>
 <p class = "warning"><%= flash[:warning] %></p>
<% end %>

<% if flash[:alert] %>
 <p class = "alert"><%= flash[:alert] %></p>
<% end %>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>タイトル</th>
      <th>開始日</th>
      <th>終了日</th>
      <th>終日</th>
      <th>スケジュール更新日時</th>
      <th>確認</th>
      <th>編集</th>
      <th>削除</th>
    </tr>
  </thead>
  
<tbody>
  <% @schedules.each do |schedule| %>
   <tr>
    <td><%= schedule.id %></td>
    <td><%= schedule.title %></td>
    <td><%= schedule.startDate.strftime('%Y年%m月%d日') %></td>
    <td><%= schedule.endDate.strftime('%Y年%m月%d日') %></td>
    <td align="center"><% if schedule.allDay == "1" %>
    ○
    <% else %>
    
    <% end %>
    </td>
    <td><%= schedule.updated_at.to_s(:datetime_jp) %></td>
    <td>
     <%= link_to "確認", schedule %>
    </td>
    <td>
     <%= link_to "編集", [:edit, schedule] %>
    </td>
    <td>
     <%= link_to "削除", schedule, data: {turbo_method: :delete, turbo_confirm: "本当に削除しますか？"} %>
    </td>
    
   </tr>
  <% end %>
 </tbody>
</table>

<p class="link"><%= link_to "スケジュール新規登録", :new_schedule %></p>

app/views/schedules/new.html.erb
<h3 class="title">スケジュール新規作成</h3>

<% if flash[:alert] %>
 <p class = "alert"><%= flash[:alert] %></p>
<% end %>

<%= render "shared/error", obj: @schedule %>

<%= form_with model: @schedule do |f| %>
 <table>
  <tr>
   <th><%= f.label :title , "タイトル" %></th>
   <td><%= f.text_field :title, style: "width:100%" %></td>
  </tr>
   
  <tr>
   <th><%= f.label :startDate , "開始日" %></th>
   <td><%= f.date_field :startDate, style: "width:100%" %></td>
  </tr>
   
  <tr>
   <th><%= f.label :endDate , "終了日" %></th>
   <td><%= f.date_field :endDate, style: "width:100%" %></td>
  </tr>
   
  <tr>
   <th><%= f.label :allDay , "終日" %></th>
   <td align="center"><%= f.check_box :allDay %><br>
   終日の場合はチェックを入れます</td>
  </tr>
  
  <tr>
   <th class="memo"><%= f.label :memo , "スケジュールメモ" %></th>
   <td><%= f.text_area :memo, style: "height: 200px; width:100%" %></td>
  </tr>
 </table>
 
 <div>
  <ul style="list-style: none;">
   <li><%= f.submit "スケジュールを新規登録する", style: "font-size: 15px"%></li>
   <li><%= link_to "スケジュール一覧に戻る", :schedules %></li>
  </ul>
 </div>
<% end %>

app/views/schedules/show.html.erb
<h3 class="title">スケジュール詳細</h3>

<table>
 <tr>
  <th>タイトル</th>
  <td><%= @schedule.title %></td>
 </tr>
 
 <tr>
  <th>開始日</th>
  <td><%= @schedule.startDate.strftime('%Y年%m月%d日') %></td>
 </tr>
 
 <tr>
  <th>終了日</th>
  <td><%= @schedule.endDate.strftime('%Y年%m月%d日') %></td>
 </tr>
 
 <tr>
  <th>終日</th>
  <td align="center"><% if @schedule.allDay == "1" %>
    ○
    <% else %>
    
    <% end %></td>
 </tr>
 
 <tr>
  <th>スケジュールメモ</th>
  <td><%= @schedule.memo %></td>
 </tr>
</table>

<div>
 <ul style="list-style: none;">
  <li><%= link_to "スケジュール一覧に戻る", :schedules %></li>
  <li><%= link_to "スケジュールを編集する", :edit_schedule %></li>
  <li><%= link_to "スケジュールを削除する", schedule_path(@schedule.id), data: {turbo_method: :delete, turbo_confirm: "本当に削除しますか？"} %></li>
 </ul>
 
</div>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
 <% obj.errors.full_messages.each do |message| %>
  <ul>
   <li><%= message %></li>
  </ul>
 <% end %>
<% end %>